---
title: "Exercise 6"
author: "Jai Broome"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    html_document:
        toc: true
        number_sections: true
---

```{r dependencies, message=FALSE}
require(knitr)
require(ggplot2)
require(kernlab)
```

# Support Vector Machines

## Example Dataset 1

```{r read-data}
ex6data1 <- read.csv("../data/ex6data/ex6data1.csv")
x <- as.matrix(ex6data1[, 2:1])
y <- as.matrix(ex6data1[, 3])
ex6data1[, 3] <- as.factor(ex6data1[, 3])
```

```{r explore-data1}
g1 <- ggplot(data = ex6data1, aes(V1, V2, color = V3, shape = V3)) + 
    geom_point()
g1
```

```{r}
linSvm1 <- ksvm(x, 
                y, 
                C = 1,
                type = "C-svc",
                kernel = "vanilladot", 
                kpar = list())
plot(linSvm1, data = x)
```

```{r temp-chunk} 
#not working
plot(scale(linSvm1), data = x)
w <- colSums(coef(linSvm1)[[1]] * ex6data1[unlist(alphaindex(linSvm1)), 2:1])
b <- b(linSvm1)
abline(b/w[1],-w[2]/w[1])
abline((b+1)/w[1],-w[2]/w[1],lty=2)
abline((b-1)/w[1],-w[2]/w[1],lty=2)
```


```{r}
linSvm2 <- ksvm(x = ex6data1[, 2:1], 
                y = ex6data1[, 3], 
                C = 100,
                type = "C-svc",
                kernel = "vanilladot", 
                kpar = list())
plot(linSvm2, data = ex6data1[, 2:1])
```

## SVM with Gaussian Kernels

## Gaussian Kernel

```{r read_chunk}
read_chunk("ex6_chunks.R")
```

```{r gaussian-kernel}
```

Because the built-in Gaussian kernel function in `kernlab` takes a different `sigma` parameter, I've defined a function that will make it comparable to the way it's calculated in the assignment.

```{r sigma-transformation}
```

```{r gk-test}
x1 <- c(1, 2, 1)
x2 = c(0, 4, -1)
sigma = 2
gk(x1, x2, sigma) 
rbf <- rbfdot(sigTransform(sigma))
rbf(x1, x2)
```

This value should be about 0.324652
