---
title: "Exercise 5"
author: "Jai Broome"
date: "May 21, 2016"
output: html_document
---

```{r dependencies, message = FALSE}
require(R.matlab)
require(ggplot2)
```
The `.mat` files have already been read in and saved as `.csv`s since Knitr doesn't play nice with `R.matlab`.
```{r}
train <- read.csv("../data/ex5train.csv")
val <- read.csv("../data/ex5val.csv")
test <- read.csv("../data/ex5test.csv")

g <- ggplot(data = train, aes(X, y)) +
    geom_point(shape = 4, color = "red", size = 3) +
    labs(title = "Figure 1: Training Data", 
         x = "Change in water level (X)", 
         y = "Water flowing out of the dam (y)")
g
```


```{r cache=FALSE}
knitr::read_chunk('../ex1/ex1_chunks.R')
```
```{r lin-reg-cost-func}
```

```{r gradient-check}
theta <- c(1,1)
X <- cbind(1, train$X)
y <- train$y
computeCost(X, y, theta)
```
This yields a different set of values than the homework, maybe because of some value of lambda in the submission script
```{r optim}
learnedTheta <- optim(par = theta,
      fn = function(par){computeCost(X, y, par, lambda = 0)$J},
      gr = function(par){computeCost(X, y, par, lambda = 0)$gradient},
      method = "BFGS", control = list(maxit = 400))
```

```{r plot-learnedTheta}
g + geom_abline(slope = learnedTheta$par[2], intercept = learnedTheta$par[1])

lm(y ~ X + 1, train)$coefficients
learnedTheta$par
```
`learnedTheta` matches the coefficients from `R`'s built-in linear regression function
