---
title: "Exercise 7"
author: "Jai Broome"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    html_document:
        toc: true
        number_sections: true
---

```{r dependencies, message=FALSE}
require(ggplot2)
require(knitr)
require(tidyr)
read_chunk("ex7_chunks.R")
```

# $K$-means Clustering

## Implementing $K$-means

### Finding closest centroids

```{r read-data2}
ex7data2 <- read.csv("../data/ex7data/ex7data2.csv")
```

```{r explore-data}
g1 <- ggplot(ex7data2, aes(V1, V2)) + geom_point()
g1
```


```{r min-Eu-dist}
```

```{r test-min-distance}
initial_centroids <- matrix(c(3, 3, 6, 2, 8, 5), 3, 2, TRUE)
minEuDist(ex7data2[15,], initial_centroids)
```

```{r find-closest-centroids}
```

```{r test-find-centroids}
idx <- findClosestCentroids(ex7data2, initial_centroids)
idx[1:3]
```

### Computing centroid means

```{r compute-centroids}
```

```{r test-compute-centroids}
computeCentroids(ex7data2, idx, initial_centroids)
```


## $K$-means on example dataset

```{r k-means}
```

```{r test-k-means}
runKMeans <- kMeans(ex7data2, initial_centroids, 10)

ex7data2 <- cbind(ex7data2, K = as.factor(runKMeans[nrow(runKMeans), 1:300]))
```

```{r plot-test-k-means}
g2 <- ggplot(ex7data2, aes(V1, V2, color = K)) + 
    geom_point(alpha = .4) + 
    geom_line(data = as.data.frame(runKMeans[, 301:302]), 
              mapping = aes(V1, V2, color = "1")) +
    geom_line(data = as.data.frame(runKMeans[, 303:304]), 
              mapping = aes(V1, V2, color = "2")) +
    geom_line(data = as.data.frame(runKMeans[, 305:306]), 
              mapping = aes(V1, V2, color = "3")) +
    geom_point(data = as.data.frame(runKMeans[, 301:302]),
               aes(V1, V2, color = "1"), shape = 4, size = 3) + 
    geom_point(data = as.data.frame(runKMeans[, 303:304]),
               aes(V1, V2, color = "2"), shape = 4, size = 3) +
    geom_point(data = as.data.frame(runKMeans[, 305:306]),
               aes(V1, V2, color = "3"), shape = 4, size = 3)
g2 
```

## Random initialization

```{r}

```

## Image compression with K-means

### $K$-means on pixels

```{r}

```

### Optional (ungraded) exercise: Use your own image

```{r}

```

# Principal Component Analysis